# Egern 简易配置 by ic58n 24/02/06
# 识别号：1.16.0-286-cn
# 
#
#
hide_vpn_icon: true
geoip_db_url: https://gitlab.com/Masaiki/GeoIP2-CN/-/raw/release/Country.mmdb
asn_db_url: https://github.com/P3TERX/GeoLite.mmdb
dns_servers:
- 8.8.8.8
- 1.1.1.1
- 119.29.29.29
- 223.5.5.5
- 114.114.114.114
- 101.101.101.101
- 101.6.6.6
policy_groups:
- select:
    name: 节点选择
    policies:
    - 手动选择
    - 自动选择
    - 负载均衡
    flatten: false
    filter: ''
    icon: https://raw.githubusercontent.com/IC58G/vpn_tool/main/Resource/Icon/other/AAEX.png
- external:
    name: 手动选择
    type: select
    urls:
    - 订阅地址
    filter: ^((?!(账号|试用|流量|网址|最新|域名|剩余|更换|套餐)).)*$
    icon: https://raw.githubusercontent.com/IC58G/vpn_tool/main/Resource/Icon/other/Cylink.png
- select:
    name: 广告屏蔽
    policies:
    - REJECT
    icon: https://raw.githubusercontent.com/IC58G/vpn_tool/main/Resource/Icon/other/Adblock.png
- external:
    name: 人工智能
    type: select
    urls:
    - 订阅地址
    filter: (?i)(美国|美國|US|States|American|日本|JP|Japan|韩国|韓國|南朝鲜|KR|Korean|台湾|台灣|TW|Taiwan)
    icon: https://raw.githubusercontent.com/IC58G/vpn_tool/main/Resource/Icon/other/Ark.png
- select:
    name: Apple服务
    policies:
    - 国内服务
    - 国际服务
    icon: https://raw.githubusercontent.com/IC58G/vpn_tool/main/Resource/Icon/Apple/Apple.png
- select:
    name: 国内服务
    policies:
    - DIRECT
    flatten: false
    filter: ''
    icon: https://raw.githubusercontent.com/IC58G/vpn_tool/main/Resource/Icon/flag/CN.png
- select:
    name: 地理位置
    policies:
    - 国内服务
    - 国际服务
    icon: https://raw.githubusercontent.com/IC58G/vpn_tool/main/Resource/Icon/other/Location.png
- select:
    name: 国际服务
    policies:
    - 手动选择
    - 自动选择
    icon: https://raw.githubusercontent.com/IC58G/vpn_tool/main/Resource/Icon/other/Global.png
- select:
    name: 国际媒体
    policies:
    - 国际服务
    icon: https://raw.githubusercontent.com/IC58G/vpn_tool/main/Resource/Icon/other/Streaming.png
- select:
    name: 国内媒体
    policies:
    - 国内服务
    filter: (?i)(台湾|台灣|TW|Taiwan|香港|HK|Hong Kong)
    icon: https://raw.githubusercontent.com/IC58G/vpn_tool/main/Resource/Icon/other/StreamingCN.png
- external:
    name: 港台番剧
    type: select
    urls:
    - 订阅地址
    filter: (?i)(台湾|台灣|TW|Taiwan|香港|HK|Hong Kong)
    icon: https://raw.githubusercontent.com/IC58G/vpn_tool/main/Resource/Icon/other/StreamingSE.png
- external:
    name: 自动选择
    type: auto_test
    urls:
    - 订阅地址
    filter: ^((?!(账号|试用|流量|网址|最新|域名|剩余|更换|套餐)).)*$
    interval: 600
    icon: https://raw.githubusercontent.com/IC58G/vpn_tool/main/Resource/Icon/other/Ark.png
- external:
    name: 负载均衡
    type: load_balance
    urls:
    - 订阅地址
    filter: ^((?!(账号|试用|流量|网址|最新|域名|剩余|更换|套餐)).)*$
    icon: https://raw.githubusercontent.com/IC58G/vpn_tool/main/Resource/Icon/other/ASN.png
rules:
- rule_set:
    match: https://raw.githubusercontent.com/IC58G/vpn_tool/main/Resource/Rule/Advertising.list
    policy: 广告屏蔽
- rule_set:
    match: https://raw.githubusercontent.com/IC58G/vpn_tool/main/Resource/Rule/Ai.list
    policy: 人工智能
- rule_set:
    match: https://raw.githubusercontent.com/IC58G/vpn_tool/main/Resource/Rule/Apple.list
    policy: Apple服务
- rule_set:
    match: https://raw.githubusercontent.com/IC58G/vpn_tool/main/Resource/Rule/China.list
    policy: 国内服务
- rule_set:
    match: https://raw.githubusercontent.com/IC58G/vpn_tool/main/Resource/Rule/Location.list
    policy: 地理位置
- rule_set:
    match: https://raw.githubusercontent.com/IC58G/vpn_tool/main/Resource/Rule/Overseas.list
    policy: 国际服务
- rule_set:
    match: https://raw.githubusercontent.com/IC58G/vpn_tool/main/Resource/Rule/Streaming.list
    policy: 国际媒体
- rule_set:
    match: https://raw.githubusercontent.com/IC58G/vpn_tool/main/Resource/Rule/StreamingCN.list
    policy: 国内媒体
- rule_set:
    match: https://raw.githubusercontent.com/IC58G/vpn_tool/main/Resource/Rule/StreamingSE.list
    policy: 港台番剧
- geoip:
    match: CN
    policy: 国内服务
- default:
    policy: 国际服务
mitm:
  enabled: true
  ca_p12: egern.p12
  ca_passphrase: egern
modules:
- name: Script-Hub
  url: https://raw.githubusercontent.com/Script-Hub-Org/Script-Hub/main/modules/script-hub.surge.sgmodule
  enabled: true
- name: Sub-Store
  url: https://raw.githubusercontent.com/sub-store-org/Sub-Store/master/config/Surge.sgmodule
  enabled: true
- name: BoxJs
  url: https://raw.githubusercontent.com/chavyleung/scripts/master/box/rewrite/boxjs.rewrite.surge.sgmodule
  enabled: true
