#!name=Mac应用激活服务
#!desc=支持 LemonSqueezy、Paddle 类型
#!icon=https://raw.githubusercontent.com/deezertidal/private/main/icons/Plugallery.png
#!homepage=https://github.com/IC58G/vpn_tool
#!author=89996462

[MITM]
hostname = *.lemonsqueezy.com, *.paddleapi.com, api.elpass.app, *.elpass.app, *.akamaized.net, *.scdn.co, *.scdn.co, *.scdn.co, *.raycast.com

[Script]
lemonSqueezy-activate-api.lemonsqueezy.com = type=http-request,pattern=^https://api.lemonsqueezy.com/v1/licenses/activate,requires-body=1,max-size=0,debug=1,script-path=https://raw.githubusercontent.com/IC58G/vpn_tool/main/Resource/Script/m/activator.js
lemonSqueezy-validate-api.lemonsqueezy.com = type=http-request,pattern=^https://api.lemonsqueezy.com/v1/licenses/validate,requires-body=1,max-size=0,debug=1,script-path=https://raw.githubusercontent.com/IC58G/vpn_tool/main/Resource/Script/m/activator.js
paddle-activate-v3.paddleapi.com = type=http-request,pattern=^https://v3.paddleapi.com/3.2/license/activate,requires-body=1,max-size=0,debug=1,script-path=https://raw.githubusercontent.com/IC58G/vpn_tool/main/Resource/Script/m/activator.js
paddle-validate-v3.paddleapi.com = type=http-request,pattern=^https://v3.paddleapi.com/3.2/license/verify,requires-body=1,max-size=0,debug=1,script-path=https://raw.githubusercontent.com/IC58G/vpn_tool/main/Resource/Script/m/activator.js
elpass-activate-api.elpass.app = type=http-request,pattern=^https://api.elpass.app/device/activate-with-key,requires-body=1,max-size=0,debug=1,script-path=https://raw.githubusercontent.com/IC58G/vpn_tool/main/Resource/Script/m/activator.js
elpass-management-api.elpass.app = type=http-request,pattern=^https://api.elpass.app/device/management,requires-body=1,max-size=0,debug=1,script-path=https://raw.githubusercontent.com/IC58G/vpn_tool/main/Resource/Script/m/activator.js
elpass-init-api.elpass.app = type=http-request,pattern=^https://api.elpass.app/device/init,requires-body=1,max-size=0,debug=1,script-path=https://raw.githubusercontent.com/IC58G/vpn_tool/main/Resource/Script/m/activator.js
spotify-*-audio-akp-quic-spotify-com.akamaized.net = type=http-request,pattern=^https://audio-akp-quic-spotify-com.akamaized.net/*,requires-body=1,max-size=0,debug=1,script-path=https://raw.githubusercontent.com/IC58G/vpn_tool/main/Resource/Script/m/activator.js
spotify-*-audio-fa.scdn.co = type=http-request,pattern=^https://audio-fa.scdn.co/*,requires-body=1,max-size=0,debug=1,script-path=https://raw.githubusercontent.com/IC58G/vpn_tool/main/Resource/Script/m/activator.js
spotify-*-creativeservice-production.scdn.co = type=http-request,pattern=^https://creativeservice-production.scdn.co/*,requires-body=1,max-size=0,debug=1,script-path=https://raw.githubusercontent.com/IC58G/vpn_tool/main/Resource/Script/m/activator.js
spotify-*-audio4-fa.scdn.co = type=http-request,pattern=^https://audio4-fa.scdn.co/*,requires-body=1,max-size=0,debug=1,script-path=https://raw.githubusercontent.com/IC58G/vpn_tool/main/Resource/Script/m/activator.js
raycast-activate-backend.raycast.com = type=http-response,pattern=^https://backend.raycast.com/api/v1/me,requires-body=1,max-size=0,debug=1,script-path=https://raw.githubusercontent.com/IC58G/vpn_tool/main/Resource/Script/m/activator.js
raycast-me/trial_status-backend.raycast.com = type=http-request,pattern=^https://backend.raycast.com/api/v1/me/trial_status,requires-body=1,max-size=0,debug=1,script-path=https://raw.githubusercontent.com/IC58G/vpn_tool/main/Resource/Script/m/activator.js

Paddle1 = type=http-request,pattern=^https://v3.paddleapi.com/3.2/license/verify,requires-body=1,max-size=0,debug=1,script-path=https://raw.githubusercontent.com/IC58G/vpn_tool/main/Resource/Script/m/paddle_act.js
Paddle2 = type=http-request,pattern=^https://v3.paddleapi.com/3.2/license/activate,requires-body=1,max-size=0,debug=1,script-path=https://raw.githubusercontent.com/IC58G/vpn_tool/main/Resource/Script/m/paddle_act.js

elpass = type=http-request,pattern=^https://api.elpass.app/device/management,requires-body=1,max-size=0,debug=1,script-path=https://raw.githubusercontent.com/IC58G/vpn_tool/main/Resource/Script/m/paddle_act.js
elpass1 = type=http-request,pattern=^https://api.elpass.app/device/init,requires-body=1,max-size=0,debug=1,script-path=https://raw.githubusercontent.com/IC58G/vpn_tool/main/Resource/Script/m/paddle_act.js
elpass2 = type=http-request,pattern=^https://api.elpass.app/device/activate-with-key,requires-body=1,max-size=0,debug=1,script-path=https://raw.githubusercontent.com/IC58G/vpn_tool/main/Resource/Script/m/paddle_act.js

MacUpdater = type=http-request,pattern=https://.*?.execute-api.*.amazonaws.com/default/meddle-activate,requires-body=1,max-size=0,debug=1,script-path=https://raw.githubusercontent.com/IC58G/vpn_tool/main/Resource/Script/m/paddle_act.js
MacUpdaterDeac = type=http-request,pattern=https://.*?.execute-api.*.amazonaws.com/default/meddle-deactivate,requires-body=1,max-size=0,debug=1,script-path=https://raw.githubusercontent.com/IC58G/vpn_tool/main/Resource/Script/m/paddle_act.js
MacUpdaterAuthorization = type=http-request,pattern=https://.*?.execute-api.*.amazonaws.com/default/meddle-authenticate,requires-body=1,max-size=0,debug=1,script-path=https://raw.githubusercontent.com/IC58G/vpn_tool/main/Resource/Script/m/paddle_act.js
