#!name=Spotify 解锁限制
#!desc=

[MITM]
hostname = spclient.wg.spotify.com

[Script]
spotify-json = type=http-request,pattern=^https:\/\/spclient\.wg\.spotify\.com\/(artistview\/v1\/artist|album-entity-view\/v2\/album)\/,requires-body=0,script-path=https://raw.githubusercontent.com/IC58G/Q/master/Resource/Script/a/spotify-json.js
spotify-proto = type=http-response,pattern=^https:\/\/spclient\.wg\.spotify\.com\/(bootstrap\/v1\/bootstrap|user-customization-service\/v1\/customize)$,requires-body=1,binary-body-mode=1,max-size=0,script-path=https://raw.githubusercontent.com/IC58G/Q/master/Resource/Script/a/spotify-proto.js,script-update-interval=0